[package]
name = "parenchyma"
version = "0.0.2"
authors = ["Jony <jonysy@users.noreply.github.com>"]
keywords = ["backend", "computation", "opencl", "cuda", "hpc"]
categories = []
description = "A high-performance computing (HPC) framework"
documentation = "https://docs.rs/parenchyma"
repository = "https://github.com/lychee-eng/parenchyma"
license = "MIT/Apache-2.0"

[features]
unstable_alloc = [] # faster but unstable memory allocation on native machines

[workspace]
members = [
    "./frameworks/cuda",
    "./frameworks/opencl",
    "./frameworks/native"
]