[package]
name = "parenchyma"
version = "0.0.2"
authors = ["Jony <jonysy@users.noreply.github.com>"]
keywords = ["backend", "computation", "opencl", "cuda", "hpc", "high-performance-computing"]
categories = []
license = "MIT/Apache-2.0"

[features]
unstable_alloc = [] # faster but unstable memory allocation on native machines

[workspace]
members = [
    # Backend support
    "./backends/cuda",
    "./backends/opencl",

    # Backend extensions
    "./extensions/array",

    # Frameworks
    "./frameworks/cuda", 
    "./frameworks/cuda-sys", 
    "./frameworks/opencl", 
    "./frameworks/opencl-sys"
]