[package]
name = "cuda"
description = "A safe wrapper around the CUDA 8 driver API"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies.cuda-sys]
path = "../cuda-sys"
version = "0.1.0"
