[package]
name = "parenchyma-opencl"
version = "0.0.2"
authors = ["Jony <jonysy@users.noreply.github.com>"]
keywords = ["backend", "computation", "hpc"]
categories = []
license = "MIT/Apache-2.0"

[dependencies]
enum_primitive = "0.1.1"

[dependencies.parenchyma]
path = "../../"
version = "0.0.2"