[package]
name = "opencl"
description = "A safe OpenCL wrapper"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies.opencl-sys]
path = "../opencl-sys"
version = "0.1.0"